version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Type: Dependencies"
      - "Type: CI"

  - package-ecosystem: "docker"
    directories:
      - "/humble"
      - "/iron"
      - "/jazzy"
    schedule:
      interval: "daily"
